version: '3'
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: random_coffee
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
